apiVersion: 1
datasources:
  - name: loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true

  - name: victoriametrics
    type: prometheus
    access: proxy
    orgId: 1
    uid: vm
    url: http://victoriametrics:8428
    isDefault: true
    editable: true