version: '3.7'

volumes:
    vm_data: {}
    grafana_data: {}
    loki_data: {}

services:
  victoriametrics:
    image: victoriametrics/victoria-metrics
    command:
      - '--httpListenAddr=:8428'  # Listen on all interfaces for HTTPS
      - '--promscrape.config=/etc/victoriametrics/victoriametrics.yaml'
    container_name: victoriametrics
    ports:
      - "8428:8428"
    volumes:
      - vm_data:/victoriametrics-data
      - ./victoriametrics.yaml:/etc/victoriametrics/victoriametrics.yaml:ro
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_ROOT_URL=${GRAFANA_URL:-http://localhost:3000}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PROVISIONING_ENABLED=true  # Enable datasource provisioning
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-bottoken}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-10000}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - ./grafana/provisioning/alerting/contactpoints.yaml:/etc/grafana/provisioning/alerting/contactpoints.yaml:ro
      - ./grafana/provisioning/alerting/rules.yaml:/etc/grafana/provisioning/alerting/rules.yaml:ro
      - ./grafana/provisioning/alerting/templates.yaml:/etc/grafana/provisioning/alerting/templates.yaml:ro
      - ./grafana/provisioning/alerting/notification_policy.yaml:/etc/grafana/provisioning/alerting/notification_policy.yaml:ro
    depends_on:
      - loki
      - victoriametrics
      - promtail
      - node-exporter
      - blackbox-exporter
  loki:
    image: grafana/loki:latest
    container_name: loki
    user: root
    command:
      - '--config.file=/loki/loki.yaml'  # Use configuration file
    ports:
      - "3100:3100"
    volumes:
      - ./loki.yaml:/loki/loki.yaml:ro
      - loki_data:/loki/data

  promtail:
    image: grafana/promtail
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail.yaml:/etc/promtail/config.yaml:ro
    command: -config.file=/etc/promtail/config.yaml


  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro  # Optional configuration for advanced customization
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"  # Expose Node Exporter metrics endpoint

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    restart: unless-stopped
    command:
      - '--config.file=/etc/blackbox/blackbox.yaml'  # Path to your configuration file
    volumes:
      - ./blackbox.yaml:/etc/blackbox/blackbox.yaml:ro  # Mount your configuration file
    ports:
      - "9115:9115" 

  validators-exporter:
    build: ./validators-exporter
    container_name: validators-exporter
    restart: unless-stopped
    volumes:
      - ./validators-exporter/config.toml:/config/config.toml:ro
    ports:
      - "9560:9560" # Adjust the port mapping as necessary
