apiVersion: 1

datasources:
  # Define datasource for VictoriaMetrics
- name: VictoriaMetrics
  type: prometheus
  access: proxy
  url: http://victoriametrics:8428
  isDefault: true  # Set as default datasource

# Define datasource for Loki
- name: Loki
  type: loki
  access: proxy
  url: http://loki:3100
  jsonData:
    maxLines: 1000