apiVersion: 1
contactPoints:
    - orgId: 1
      name: telegram
      receivers:
        - uid: 1
          type: telegram
          settings:
            bottoken: '${TELEGRAM_BOT_TOKEN}'
            chatid: |
              -${TELEGRAM_CHAT_ID}
            disable_notification: false
            disable_web_page_preview: false
            protect_content: false
            message: '{{ template "telegram.message_common" . }}'
            parse_mode: HTML
          disableResolveMessage: false